### DISCUSSION TITLE
POCASAG eigene RIC Filtern

### DISCUSSION THREAD

**Discussion by bixicy** [BOSWatch/BW3-Core#80] [Q&A] [answered]
Hi,
wie kann ich über POCSAG meine eigenen RICs ausfiltern, so dass alles andere nicht mehr durchkommt?

Habe mir zwar die docs durchgelesen, aber konnte ich nicht wirklich finden.

**Comment by Schrolli91** [comment, marked as answer]
Du willst also, dass NUR noch deine durchkommt?

Dann versuch mal sowas in der Art: (wobei in `regex:` natürlich deine RIC stehen sollte)
```
- type: module
  res: filter.regexFilter
  config:
    - name: "own ric filter"
      checks:
        - field: ric
          regex: "123456"
```

**Reply by bixicy** [reply]
Ja, genau. Sollen nur meine durchkommen.
Mehrfachauswahl wie in BW2 Komma getrennt? Oder jeweils field und regex den Block kopieren und RIC eintragen?

Kann das mit eigener RIC schlecht testen.

**Reply by Schrolli91** [reply]
Fast - Beispiel:

```
- type: module
  res: filter.regexFilter
  config:
    - name: "own ric filter"
      checks:
        - field: ric
          regex: "123456"
    - name: "other ric filter"
      checks:
        - field: ric
          regex: "987654"
       ...
```

Aus der Doku: https://docs.boswatch.de/modul/regex_filter.html

```
Folgendes gilt:

- Die Filter werden nacheinander abgearbeitet
- Innerhalb des Filters werden die Checks nacheinander abgearbeitet
- Sobald ein einzelner Check fehlschlägt ist der ganze Filter fehlgeschlagen
- Sobald ein Filter mit all seinen Checks besteht, wird mit der Ausführung des Routers fortgefahren
- Sollten alle Filter fehlschlagen wird die Ausführung des Routers beendet
```
Vereinfacht kann man sagen, dass einzelne Filter ODER-verknüpft und die jeweiligen Checks UND-verknüpft sind.

**Reply by bixicy** [reply]
Danke

**Reply by Schrolli91** [reply]
Hab nochmal bearbeitet - bitte beachten.
Nicht mehrere Checks, sondern mehrere Filter anlegen.
Die Checks sind UND Verknüpft und müssen immer ALLE erfüllt sein.

**Reply by bixicy** [reply]
Wollte gerade schreiben, dass noch andere durchkommen. Ich passe nochmal an.

**Reply by bixicy** [reply]
Habe das jetzt so, kommen aber noch immer andere RICs durch


```
  - type: module
    res: filter.regexFilter
    config:
      - name: "own ric filter1"
        checks:
          - field: ric
            regex: "12345678"
      - name: "own ric filter2"
        checks:
          - field: ric
            regex: "23456789"

```
Auch wenn ich nur eine RIC eintrage kommen alle anderen auch mit durch.
