### ISSUE TITLE
BosWatch stürzt ab - Syntax error server.yaml

### ISSUE THREAD

**Issue by Gonz01990** [BOSWatch/BW3-Core#100]
Hallo zusammen, 

ich habe ein Problem mit der Einbindung des Telegram Plugins. Nachdem ich das Plugin an die server.yaml angefügt habe, stürzt das Skript immer ab. Ohne den Teil läuft alles augenscheinlich erstmal. Ich denke ich mache irgendetwas falsch. Ich habe bereits Stunden die Doku und das Forum gewälzt. Vielen Dank für die Hilfe

Hier mal die Fehlermeldung
19.10.2022 12:38:03,637 - configYaml      [ERROR   ] syntax error in config file: /opt/boswatch3/boswatch/../config/server.yaml

Hier mal meine server.yaml
```
server:
  port: 8080
  name: BW3 Server        # name of the BW3 Server instance
  useBroadcast: no        # serve server ip on broadcast request

alarmRouter:
- Router 1

router:
- name: Router 1
  route:
  - type: module
    res: filter.modeFilter
    name: Filter Fms/Pocsag
    config:
      allowed:
        - fms
        - pocsag
  - type: plugin
   name: Telegram Plugin
   res: telegram
   config:
     message_pocsag: "{RIC}({SRIC})\n{MSG}"
     botToken: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      chatIds:
       - "-XXXXXXXX"

```
