### ISSUE TITLE
Plugin not found (telegram)

### ISSUE THREAD

**Issue by Rossibrother** [BOSWatch/BW3-Core#107]
Hey, ich bekomme diesen Fehler:

```
02.02.2023 16:22:32,270 - routerManager   [ERROR   ] plugin not found: telegram
02.02.2023 16:22:32,271 - bw_server       [CRITICAL] Error while building routers
02.02.2023 16:22:32,271 - bw_server       [ERROR   ] BOSWatch interrupted by an error
```

wenn ich den Server starten will.
Woran kann das liegen?

**Comment by janspeller** [comment]
Vermutlich fehlte hier das Python Modul für Telegram, korrekt? @Rossibrother

**Comment by Rossibrother** [comment]
Dachte ich, aber es wird immer noch nicht gefunden, hab alles versucht was in den anderen issues dazu steht hat aber leider nichts geklappt.

**Comment by Schrolli91** [comment]
Dann zeig mal deine config dazu bitte

**Comment by Rossibrother** [comment]
```
server:
  port: 8080
  name: BW3 Server        # name of the BW3 Server instance
  useBroadcast: no        # serve server ip on broadcast request

alarmRouter:
- Router 1

router:
- name: Router 1
  route:
- type: plugin
      name: Telegram Plugin
      res: telegram
      config:
        message_pocsag: "{RIC}({SRIC})\n{MSG}"
        botToken: "bot_token"
        chatIds:
          - "chatId"
```

**Comment by Schrolli91** [comment]
Nutzt du aktuell den dev Branch?
Check mal ob es i Plugin Ordner einen telegram Unterordner gibt bitte.
Eigentlich sehe ich keinen Grund, wieso das Plugin nicht gefunden werden sollte.

**Comment by Rossibrother** [comment]
Ich benutze den dev Branch, im Ordner ist die telegram.py, andere Plugins z.b. http funktionieren ohne Probleme

**Comment by janspeller** [comment]
Hast du das benötigte modul für telegram installiert? Mir ist letztens bei einer Neuinstallation mal aufgefallen, dass es da mit der neusten version probleme gibt.

@Schrolli91 Ich bin hier an einer lösung mit einer anderen Bibliothek dran, python-telegram-bot hat mit der v20 einen relativ großen API-Change gemacht, für einfaches "senden" von Nachrichten wird die Bibliothek viel zu groß. Alternatives Plugin ist bei mir seit ca. 2 Wochen im Test.

**Comment by PeterLaemmle** [comment]
Alternativ kann man die alte Version wie folgt erzwingen:
`pip install python-telegram-bot==13.13`

**Comment by KoenigMjr** [comment]
Hat noch wer Interesse an einer Problemlösung? Hab ein Telegram-Skript neu aufgesetzt ohne Bibliothek - funktioniert für mich und ZVEI, habe es aber für alle Arten der Nachrichten ausgelegt - aber dann würde es noch testen brauchen :)
In der Config aber 1:1 vom alten Skript übernehmbar, auch Doku bleibt gleich.

**Comment by sm7tix** [comment]
I get the same error now when trying on Raspbian Trixie.
Tried pip3 install python-telegram-bot and version 12.8 and 13.13. And i tried the version apt install python3-python-telegram-bot. 
Plugin not found. 
Cloned and installed bw3 develop. The installer works! Good. But not the plugin.

**Comment by Schrolli91** [comment]
@KoenigMjr maybe you can assist here?

**Comment by KoenigMjr** [comment]
With my new Plugin there is no need for the python-telegram-bot plugin.

__________

**Why python-telegram-bot is not needed here?**

Because this code talks directly to the official Telegram Bot HTTP API using requests. It builds the HTTP requests by itself and implements its own queue, worker thread, retry logic, backoff and error handling. All of the features that python-telegram-bot normally provides are already implemented manually here.

Therefore: installing / using python-telegram-bot brings no benefit in this case. The code already works without any external Telegram library.

________________

Can you Help me and Copy the Log-output? Maybe with Level "debug"?

Maybe its something with Trixie. Haven't tried so far.

**Comment by KoenigMjr** [comment]
I performed a fresh installation on a Raspberry Pi OS (64-bit) Lite, based on Debian 13 ("Trixie"), to reproduce the issue.

During this re-installation, no error related to the Telegram plugin could be detected.

To rule out any potential issues with the `server_config`, I am sharing my current configuration for the Telegram plugin for cross-checking:

```
  - type: plugin
    res: telegram
    name: Telegram Plugin
    config:
      message_zvei: "{CNAME}: {DESCR}"
      startup_message: "Server up and running!"
      queue: true
      botToken: "secretTOKEN1234567890000!secret!"
      chatIds:
        - "-1234567890123"
```

Additionally, I would like to note that I found a bug in my `service_install.sh` script. This will be fixed as soon as possible in a new Pull Request (PR), but should be irrelevant for the current discussion of this specific issue.
