### ISSUE TITLE
Descriptor Bug

### ISSUE THREAD

**Issue by Smeti1** [BOSWatch/BW3-Core#31]
Bei Auswertung der ZVEI Töne im Descriptor ist ein Fehler und zwar:
Wenn jetzt z.b  zvei: "12345" kommt wird das  Feld {DESCR} Richtig mit "Test 12345" gefüllt.

Sollte aber eine zvei kommen die nicht also for: definiert ist wie z.b. "44444"
 dann wird das Feld {DESCR} Falsch mit dem letzten add: Wert gefüllt  hier: "Test 45678"

Beispiel:  server.yaml
```
# Descriptor
  - type: module
    name: Klartext
    res: descriptor
    config:
      - scanField: tone
        descrField: description
        wildcard: "{DESCR}"
        descriptions:
          - for: 12345
            add: Test 12345
          - for: 23456
            add: Test 23456
          - for: 34567
            add: Test 34567
          - for: 45678
            add: Test 45678
```

**Comment by Schrolli91** [comment]
Ist wohl wirklich ein Bug, die Doku sagt `Wenn keine Beschreibung vorhanden ist, wird im Feld descrField der Inhalt des Feldes scanField hinterlegt`

**Comment by Smeti1** [comment]
Noch was entdeckt
Sollte das Letzte add: Feld Leer sein weil man sich ja so behelfen könnte dann wir das letzte for: Feld benutzt  also im Beispiel unten kommt bei einer zvei "44444"  die "99999" als {DESCR} raus

Beispiel: server.yaml
```
# Descriptor
  - type: module
    name: Klartext
    res: descriptor
    config:
      - scanField: tone
        descrField: description
        wildcard: "{DESCR}"
        descriptions:
          - for: 12345
            add: Test 12345
          - for: 23456
            add: Test 23456
          - for: 34567
            add: Test 34567
          - for: 99999
            add: 
```
